Repository knockcat/Hacktoberfest-2022, pull requests merged in 2022-10, with the labels that each got.

#3 Added a new API and async js based project
  Personal-Chrome-Dashboard (API Based)/dashboard.png
  Personal-Chrome-Dashboard (API Based)/index.html
  Personal-Chrome-Dashboard (API Based)/manifest.json
  Personal-Chrome-Dashboard (API Based)/script.js
  Personal-Chrome-Dashboard (API Based)/style.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#15 added rang project
  rang/.eslintrc.json
  rang/.gitignore
  rang/README.md
  rang/components/Card.jsx
  rang/components/Footer.jsx
  rang/components/Navbar.jsx
  rang/data/colors.js
  rang/next.config.js
  rang/package.json
  rang/pages/_app.js
  rang/pages/color/[slug].jsx
  rang/pages/index.jsx
  rang/postcss.config.js
  rang/public/favicon.ico
  rang/public/icon.png
  rang/public/logo.svg
  rang/styles/globals.css
  rang/tailwind.config.js
  rang/yarn.lock
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#19 added image encryption project
  Image Encryption/Action Animation.png
  Image Encryption/Decrypted - Copy.jpg
  Image Encryption/Main.py
Labels: hacktoberfest, hacktoberfest-accepted

#20 Added a weather app
  Weather-app/.gitignore
  Weather-app/index.html
  Weather-app/script.js
  Weather-app/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#23 Added Simple Microservices Javaspringboot with MongoDB
  .idea/.gitignore
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  Hacktoberfest-2023.iml
  Java_Microservices/LicenseServices/.gitignore
  Java_Microservices/LicenseServices/.mvn/wrapper/maven-wrapper.jar
  Java_Microservices/LicenseServices/.mvn/wrapper/maven-wrapper.properties
  Java_Microservices/LicenseServices/mvnw
  Java_Microservices/LicenseServices/mvnw.cmd
  Java_Microservices/LicenseServices/pom.xml
  Java_Microservices/LicenseServices/src/main/java/com/microservices/licenseservices/LicenseServicesApplication.java
  Java_Microservices/LicenseServices/src/main/java/com/microservices/licenseservices/controller/LicenseController.java
  Java_Microservices/LicenseServices/src/main/java/com/microservices/licenseservices/dao/LicenseDao.java
  Java_Microservices/LicenseServices/src/main/java/com/microservices/licenseservices/dto/ResourceNotFoundException.java
  Java_Microservices/LicenseServices/src/main/java/com/microservices/licenseservices/dto/ResponseLicense.java
  Java_Microservices/LicenseServices/src/main/java/com/microservices/licenseservices/model/License.java
  Java_Microservices/LicenseServices/src/main/java/com/microservices/licenseservices/model/Status.java
  Java_Microservices/LicenseServices/src/main/java/com/microservices/licenseservices/repository/CustomLicenseRepository.java
  Java_Microservices/LicenseServices/src/main/java/com/microservices/licenseservices/repository/CustomLicenseRepositoryImpl.java
  Java_Microservices/LicenseServices/src/main/java/com/microservices/licenseservices/repository/LicenseRepository.java
  Java_Microservices/LicenseServices/src/main/resources/application.properties
  Java_Microservices/LicenseServices/src/test/java/com/microservices/licenseservices/LicenseServicesApplicationTests.java
Labels: hacktoberfest, hacktoberfest-accepted

#25 Added wordcounter app
  word_counter/About.md
  word_counter/favicon_io/favicon-16x16.png
  word_counter/favicon_io/favicon-32x32.png
  word_counter/index.html
  word_counter/index.js
  word_counter/style.css
Labels: hacktoberfest

#36 Pneumonia Detection
  Pneumonia-Detection-from-Chest-X-Ray-Images/Chest_X_Ray_Classification_(Pneumonia_Normal).ipynb
  Pneumonia-Detection-from-Chest-X-Ray-Images/Readme.md
Labels: hacktoberfest, hacktoberfest-accepted

#37 added code for calculator app using js
  calculator app/calc.js
  calculator app/index.html
Labels: hacktoberfest, hacktoberfest-accepted
